const ContactFormTypes = {
  SEND_CONTACT_FORM_START: 'SEND_CONTACT_FORM_START',
  SEND_CONTACT_FORM_SUCCESS: 'SEND_CONTACT_FORM_SUCCESS',
  SEND_CONTACT_FORM_FAILURE: 'SEND_CONTACT_FORM_FAILURE'
}

export default ContactFormTypes;